FROM python:3.11

WORKDIR /app

COPY ./src/server/requirements.txt .

RUN pip install -r requirements.txt

COPY ./src/server .
COPY ./src/modules .

EXPOSE 5000

CMD [ "flask", "--app", "main", "run", "--host=0.0.0.0", "--debug" ]