services:
  server:
    depends_on:
      - keydb
    build:
      context: ./
      dockerfile: ./src/server/dockerfile
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: ./src/server
          target: /app
          ignore:
            - dev/
        - action: rebuild
          path: ./requirements.txt
  keydb:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    volumes:
      - ./keydb.conf:/etc/keydb/keydb.conf
